// Database Statis: Master Bank Soal Kuis BitBrain (105 Pertanyaan)
const masterQuizData = [
    // --- Kategori: Pemrograman & Web Dasar ---
    { question: "Tag HTML yang digunakan untuk membuat judul utama atau terbesar adalah...", options: ["<heading>", "<h6>", "<h1>", "<head>"], answer: 2 },
    { question: "Bahasa pemrograman yang berjalan di sisi browser untuk membuat halaman menjadi interaktif adalah...", options: ["HTML", "CSS", "JavaScript", "PHP"], answer: 2 },
    { question: "Jika kamu membuat kesalahan penulisan kode di CSS, efek yang paling sering terjadi adalah...", options: ["Komputer meledak", "Tampilan web menjadi berantakan", "Kuota internet habis", "Dapat nilai A otomatis"], answer: 1 },
    { question: "Simbol yang digunakan untuk memilih elemen berdasarkan ID di CSS adalah...", options: [". (titik)", "# (pagar)", "* (bintang)", "@ (at)"], answer: 1 },
    { question: "Struktur data CSS yang digunakan untuk membuat tata letak dua dimensi (baris dan kolom) secara fleksibel adalah...", options: ["Flexbox", "Float", "Inline-block", "CSS Grid"], answer: 3 },
    { question: "Tag HTML yang digunakan untuk membuat tautan atau hyperlink ke halaman lain adalah...", options: ["<link>", "<a>", "<href>", "<nav>"], answer: 1 },
    { question: "Dalam CSS, properti yang digunakan untuk mengubah warna latar belakang sebuah elemen adalah...", options: ["color", "bg-color", "background-color", "surface-color"], answer: 2 },
    { question: "Manakah di bawah ini yang merupakan tag HTML semantik?", options: ["<div>", "<span>", "<article>", "<b>"], answer: 2 },
    { question: "Ekstensi file yang digunakan untuk menyimpan kode program JavaScript eksternal adalah...", options: [".html", ".css", ".js", ".java"], answer: 2 },
    { question: "Sifat penulisan variabel di JavaScript yang membedakan huruf besar dan huruf kecil disebut...", options: ["Case-Sensitive", "Upper-Lower", "Auto-Format", "Strict-Type"], answer: 0 },
    { question: "Metode JavaScript yang digunakan untuk menulis pesan atau melakukan debugging langsung di panel inspect browser adalah...", options: ["alert()", "console.log()", "document.write()", "print()"], answer: 1 },
    { question: "Properti CSS yang mengatur jarak di DALAM batas elemen (antara konten dan border) adalah...", options: ["margin", "padding", "border-spacing", "gap"], answer: 1 },
    { question: "Properti CSS yang mengatur jarak di LUAR batas elemen untuk memberi ruang antar elemen adalah...", options: ["margin", "padding", "outline", "space"], answer: 0 },
    { question: "Tag HTML yang digunakan untuk membungkus satu baris item di dalam sebuah daftar (list) adalah...", options: ["<ul>", "<ol>", "<li>", "<list>"], answer: 2 },
    { question: "Untuk membuat komentar di dalam kode HTML, simbol yang digunakan adalah...", options: ["// komentar", "/* komentar */", "<!-- komentar -->", "# komentar"], answer: 2 },

    // --- Kategori: Logika, Algoritma, & Javascript Advanced ---
    { question: "Keyword dalam JavaScript modern yang digunakan untuk mendeklarasikan variabel yang nilainya tidak bisa diubah kembali adalah...", options: ["var", "let", "const", "static"], answer: 2 },
    { question: "Operator logika yang digunakan untuk menyatakan kondisi 'DAN' (keduanya harus benar) di JavaScript adalah...", options: ["||", "&&", "!", "=="], answer: 1 },
    { question: "Operator logika yang digunakan untuk menyatakan kondisi 'ATAU' (salah satu benar sudah cukup) adalah...", options: ["||", "&&", "!", "++"], answer: 0 },
    { question: "Manakah struktur perulangan (loop) yang mengevaluasi kondisi di akhir blok, sehingga minimal berjalan satu kali?", options: ["for", "while", "do...while", "foreach"], answer: 2 },
    { question: "Tipe data dalam JavaScript yang hanya memiliki dua kemungkinan nilai, yaitu true atau false adalah...", options: ["String", "Number", "Boolean", "Object"], answer: 2 },
    { question: "Indeks awal dari sebuah Array di hampir seluruh bahasa pemrograman populer seperti JavaScript dan Python dimulai dari angka...", options: ["1", "0", "-1", "Kosong"], answer: 1 },
    { question: "Metode Array di JavaScript yang digunakan untuk menambahkan elemen baru ke posisi paling akhir adalah...", options: ["pop()", "push()", "shift()", "unshift()"], answer: 1 },
    { question: "Metode Array di JavaScript yang digunakan untuk menghapus elemen terakhir dari array adalah...", options: ["pop()", "push()", "shift()", "slice()"], answer: 0 },
    { question: "Struktur kondisi yang paling cocok digunakan jika kita memiliki banyak sekali percabangan nilai statis yang fix adalah...", options: ["if...else", "nested if", "switch case", "while loop"], answer: 2 },
    { question: "Apa kepanjangan dari singkatan DOM dalam JavaScript?", options: ["Data Object Model", "Document Object Model", "Digital Option Management", "Desktop Output Monitor"], answer: 1 },
    { question: "Sintaks `===` pada JavaScript membandingkan nilai berdasarkan...", options: ["Nilainya saja", "Tipe datanya saja", "Nilai dan tipe datanya sekaligus", "Lokasi memorinya"], answer: 2 },
    { question: "Fungsi bawaan JavaScript yang digunakan untuk mengubah string teks menjadi angka bulat adalah...", options: ["Math.round()", "parseInt()", "parseFloat()", "toString()"], answer: 1 },
    { question: "Cara menuliskan fungsi secara ringkas di JavaScript modern dengan simbol `=>` dinamakan...", options: ["Anonymous Function", "Callback Function", "Arrow Function", "Expression Function"], answer: 2 },
    { question: "Objek global di JavaScript yang menyediakan fungsionalitas matematika tingkat tinggi seperti pengacakan nilai adalah...", options: ["Math", "Geometry", "Algebra", "Number"], answer: 0 },
    { question: "Fungsi `Math.floor(x)` digunakan untuk...", options: ["Membulatkan angka ke atas", "Membulatkan angka ke bawah", "Mencari nilai kuadrat", "Membulatkan ke angka terdekat"], answer: 1 },

    // --- Kategori: Git & Github (Sangat relevan dengan aktivitasmu!) ---
    { question: "Perintah Git yang digunakan untuk membuat atau menginisialisasi repositori lokal baru di komputer adalah...", options: ["git clone", "git init", "git status", "git remote"], answer: 1 },
    { question: "Perintah Git yang digunakan untuk memantau file mana saja yang telah dimodifikasi atau belum masuk staging area adalah...", options: ["git status", "git log", "git diff", "git check"], answer: 0 },
    { question: "Perintah Git untuk memaketkan seluruh perubahan file di folder saat ini ke area persiapan (staging area) adalah...", options: ["git add index.html", "git add .", "git commit", "git push"], answer: 1 },
    { question: "Perintah Git yang digunakan untuk menyimpan perubahan secara permanen di riwayat lokal beserta catatannya adalah...", options: ["git save", "git upload", "git commit", "git push"], answer: 2 },
    { question: "Perintah Git yang digunakan untuk mengirimkan seluruh catatan commit lokal ke repositori online seperti GitHub adalah...", options: ["git push", "git pull", "git fetch", "git publish"], answer: 0 },
    { question: "Platform berbasis awan (cloud) paling populer milik Microsoft yang digunakan untuk menyimpan repositori Git secara online adalah...", options: ["GitLab", "Bitbucket", "GitHub", "Google Drive"], answer: 2 },
    { question: "Perintah Git yang digunakan untuk menyalin repositori online dari GitHub ke komputer lokal kamu adalah...", options: ["git copy", "git clone", "git download", "git fetch"], answer: 1 },
    { question: "Perintah Git yang digunakan untuk menarik dan memperbarui kode lokal kamu dengan kode terbaru dari GitHub adalah...", options: ["git push", "git pull", "git merge", "git update"], answer: 1 },
    { question: "Istilah untuk percabangan alur kerja kode di dalam Git dinamakan...", options: ["Tree", "Branch", "Leaf", "Root"], answer: 1 },
    { question: "Nama default yang umum digunakan untuk cabang utama sebuah proyek Git di era modern adalah...", options: ["master", "main", "root", "primary"], answer: 1 },

    // --- Kategori: Sistem Komputer & Hardware ---
    { question: "Di bawah ini yang merupakan komponen 'otak' atau pusat pemrosesan data utama pada komputer adalah...", options: ["RAM", "Processor / CPU", "SSD", "GPU"], answer: 1 },
    { question: "Komponen hardware yang berfungsi menyimpan data sementara saat aplikasi sedang berjalan (bersifat volatile) adalah...", options: ["Harddisk", "SSD", "RAM", "ROM"], answer: 2 },
    { question: "Media penyimpanan modern berkecepatan tinggi yang tidak menggunakan piringan cakram magnetik berputar adalah...", options: ["HDD", "Floppy Disk", "SSD", "CD-ROM"], answer: 2 },
    { question: "Komponen komputer yang bertanggung jawab khusus untuk mengolah grafis, rendering game, atau kecerdasan buatan adalah...", options: ["CPU", "GPU / VGA", "Sound Card", "Motherboard"], answer: 1 },
    { question: "Papan sirkuit utama tempat melekatnya seluruh komponen internal komputer seperti CPU, RAM, dan GPU dinamakan...", options: ["Motherboard", "Power Supply", "Chassis", "Heatsink"], answer: 0 },
    { question: "Alat pengetikan pada komputer yang tata letak tombol standarnya dinamakan sesuai 6 huruf baris teratas bernama...", options: ["DVORAK", "AZERTY", "QWERTY", "MALTRON"], answer: 2 },
    { question: "Komponen yang bertugas menyuplai arus listrik ke seluruh perangkat keras di dalam casing komputer adalah...", options: ["UPS", "Power Supply Unit (PSU)", "Stabilizer", "Inverter"], answer: 1 },
    { question: "Jenis memori internal komputer yang menyimpan kode boot dasar (BIOS) dan datanya tidak hilang saat komputer dimatikan adalah...", options: ["RAM", "ROM", "Cache", "VRAM"], answer: 1 },
    { question: "Perangkat keras yang berfungsi memancarkan sinyal internet nirkabel di area rumah atau kantor disebut...", options: ["Switch", "Hub", "Router / Access Point", "Modem Kabel"], answer: 2 },
    { question: "Sistem bilangan digital yang hanya menggunakan dua simbol angka, yaitu 0 dan 1 dinamakan sistem...", options: ["Desimal", "Oktal", "Heksadesimal", "Biner"], answer: 3 },

    // --- Kategori: Jaringan Komputer & Internet ---
    { question: "Protokol standar yang digunakan untuk mengamankan pengiriman data enkripsi di website (ada ikon gembok di URL) adalah...", options: ["HTTP", "HTTPS", "FTP", "SMTP"], answer: 1 },
    { question: "Apa kepanjangan dari singkatan URL di dalam dunia web?", options: ["Universal Resource Locator", "Uniform Resource Locator", "United Registry Link", "User Route Location"], answer: 1 },
    { question: "Sistem yang berfungsi menerjemahkan nama domain website (seperti google.com) menjadi alamat IP angka dinamakan...", options: ["DHCP", "DNS", "FTP", "NAT"], answer: 1 },
    { question: "Identitas berupa deretan angka unik yang dimiliki oleh setiap perangkat yang terhubung ke jaringan internet disebut...", options: ["MAC Address", "IP Address", "IMEI", "SSID"], answer: 1 },
    { question: "Protokol jaringan yang bertugas membagikan alamat IP secara otomatis kepada perangkat baru yang terhubung adalah...", options: ["DNS", "DHCP", "SSH", "ICMP"], answer: 1 },
    { question: "Perangkat lunak atau keras yang bertugas menyaring, memblokir, dan mengamankan jaringan komputer dari lalu lintas mencurigakan disebut...", options: ["Antivirus", "Firewall", "Proxy", "Gateway"], answer: 1 },
    { question: "Arsitektur jaringan internet di mana browser bertindak sebagai peminta data dan komputer server bertindak sebagai penyedia data dinamakan...", options: ["Peer-to-Peer", "Client-Server", "Ad-Hoc", "Distributed Network"], answer: 1 },
    { question: "Perintah terminal berbasis teks yang digunakan untuk menguji konektivitas atau latensi jaringan antara komputer kita dan server target adalah...", options: ["ipconfig", "ping", "traceroute", "netstat"], answer: 1 },
    { question: "Kepanjangan dari istilah jaringan berskala global WWW adalah...", options: ["World Wide Web", "World Word Web", "Web Wireless World", "Wide World Web"], answer: 0 },
    { question: "Jenis kabel jaringan lokal yang paling umum digunakan saat ini dengan konektor ujung bernama RJ-45 adalah kabel...", options: ["Koaksial", "Fiber Optic", "UTP / LAN", "Kabel Telepon"], answer: 2 },

    // --- Kategori: Sistem Operasi & Linux ---
    { question: "Sistem operasi komputer open-source yang logonya berbentuk seekor pinguin bernama Tux adalah...", options: ["Windows", "macOS", "Linux", "FreeBSD"], answer: 2 },
    { question: "Perintah dasar terminal Linux yang digunakan untuk melihat daftar file dan folder di direktori saat ini adalah...", options: ["cd", "mkdir", "ls", "pwd"], answer: 2 },
    { question: "Perintah terminal Linux yang digunakan untuk membuat sebuah folder atau direktori baru adalah...", options: ["touch", "mkdir", "rmdir", "create"], answer: 1 },
    { question: "Perintah terminal Linux yang digunakan untuk berpindah atau mengubah posisi direktori kerja kita adalah...", options: ["mv", "cp", "cd", "goto"], answer: 2 },
    { question: "Inti terdalam dari sebuah sistem operasi yang mengelola interaksi antara hardware dan software dinamakan...", options: ["Shell", "Kernel", "GUI", "Compiler"], answer: 1 },
    { question: "Sistem operasi ponsel pintar (smartphone) paling populer di dunia yang menggunakan basis dasar kernel Linux adalah...", options: ["iOS", "Windows Phone", "Android", "Symbian"], answer: 2 },
    { question: "Kombinasi tombol keyboard untuk membuka Task Manager secara langsung di Windows adalah...", options: ["Ctrl + Alt + Del", "Ctrl + Shift + Esc", "Alt + F4", "Win + Tab"], answer: 1 },
    { question: "Perintah terminal Linux yang digunakan untuk menghapus sebuah file secara permanen adalah...", options: ["rm", "del", "remove", "clear"], answer: 0 },
    { question: "Struktur direktori tertinggi atau akar pada sistem operasi Linux disimbolkan dengan karakter...", options: ["~ (tilde)", "/ (slash)", "\\ (backslash)", "# (hashtag)"], answer: 1 },
    { question: "Sistem file standar yang digunakan oleh sistem operasi Windows modern saat ini adalah...", options: ["FAT32", "exFAT", "ext4", "NTFS"], answer: 3 },

    // --- Kategori: Keamanan Siber & Database ---
    { question: "Istilah untuk kejahatan penipuan digital yang memancing korban untuk mengisi data sensitif melalui halaman web palsu disebut...", options: ["Malware", "Phishing", "DDoS", "Ransomware"], answer: 1 },
    { question: "Jenis malware berbahaya yang mengunci atau mengenkripsi data komputer korban lalu meminta uang tebusan dinamakan...", options: ["Spyware", "Trojan", "Ransomware", "Keylogger"], answer: 2 },
    { question: "Metode enkripsi kata sandi (hashing) satu arah yang sangat populer namun sekarang sudah dianggap tidak aman untuk database adalah...", options: ["SHA-256", "AES", "MD5", "RSA"], answer: 2 / 2 },
    { question: "Bahasa standar yang digunakan untuk mengelola, mengambil, dan memanipulasi data di dalam database relasional disebut...", options: ["NoSQL", "SQL", "HTML", "JSON"], answer: 1 },
    { question: "Di bawah ini yang merupakan contoh sistem manajemen database (RDBMS) open-source berbasis SQL yang sangat populer adalah...", options: ["MongoDB", "MySQL", "Redis", "Cassandra"], answer: 1 },
    { question: "Serangan siber yang membanjiri lalu lintas server dengan jutaan request palsu hingga server tumbang atau crash dinamakan...", options: ["SQL Injection", "Brute Force", "DDoS", "Man-in-the-Middle"], answer: 2 },
    { question: "Jenis database modern yang tidak menggunakan struktur tabel relasional kaku (seperti MongoDB) disebut database...", options: ["SQL", "NoSQL", "GraphDB", "FlatFile"], answer: 1 },
    { question: "Kunci unik di dalam sebuah tabel database yang menjamin bahwa tidak ada baris data yang kembar/duplikat disebut...", options: ["Foreign Key", "Primary Key", "Super Key", "Candidate Key"], answer: 1 },
    { question: "Proses verifikasi identitas pengguna menggunakan dua faktor keamanan (seperti password ditambah kode SMS) disebut...", options: ["Single Sign-On (SSO)", "Two-Factor Authentication (2FA)", "Biometric Scan", "OAuth"], answer: 1 },
    { question: "Teknik menyusupkan kode perintah SQL berbahaya ke dalam form input website untuk meretas database disebut...", options: ["Cross-Site Scripting (XSS)", "SQL Injection", "Phishing", "Buffer Overflow"], answer: 1 },

    // --- Kategori: Kecerdasan Buatan (AI) & Tren Teknologi ---
    { question: "Teknologi kecerdasan buatan berbasis teks yang mampu berdialog interaktif dan membantu pengerjaan kode pemrograman disebut...", options: ["Computer Vision", "Large Language Model (LLM)", "Expert System", "Blockchain"], answer: 1 },
    { question: "Teknologi buku besar terdesentralisasi dan aman yang menjadi fondasi utama dari ekosistem mata uang kripto (Cryptocurrency) adalah...", options: ["Cloud Computing", "AI", "Blockchain", "Data Mining"], answer: 2 },
    { question: "Mata uang kripto (digital asset) pertama di dunia yang diciptakan oleh identitas samaran bernama Satoshi Nakamoto pada tahun 2009 adalah...", options: ["Ethereum", "Bitcoin", "Solana", "Ripple"], answer: 1 },
    { question: "Format pertukaran data ringan berbentuk teks terstruktur yang paling sering digunakan dalam komunikasi API modern saat ini adalah...", options: ["XML", "CSV", "JSON", "YAML"], answer: 2 },
    { question: "Cabang ilmu AI yang berfokus pada kemampuan komputer untuk mengenali, memproses, dan menganalisis data berupa gambar atau video adalah...", options: ["Natural Language Processing", "Computer Vision", "Reinforcement Learning", "Speech Recognition"], answer: 1 },

    // --- Kategori: Humor & Tebak-tebakan Santai Anak Informatika ---
    { question: "Satu-satunya makhluk hidup yang bisa memahami isi hati dan pikiran seorang programmer adalah...", options: ["Pacar", "Dosen Wali", "ChatGPT / AI", "Rubber Duck (Bebek Karet)"], answer: 3 },
    { question: "Kenapa kacamata seorang programmer seringkali tebal dan minusnya tinggi?", options: ["Karena radiasi layar monitor", "Biar gampang melihat kesalahan (bug) sekecil apapun", "Bawaan lahir", "Efek kebanyakan begadang"], answer: 1 },
    { question: "Hewan apa yang paling dibenci dan ditakuti oleh seluruh komunitas programmer di muka bumi?", options: ["Kecoa", "Tikus", "Serangga / Bug", "Nyamuk"], answer: 2 },
    { question: "Apa alasan utama seorang mahasiswa IT seringkali jomblo atau susah mencari pacar?", options: ["Terlalu sibuk pacaran dengan text editor", "Gak punya modal", "Wajahnya mirip codingan", "Takut kena error saat PDKT"], answer: 0 },
    { question: "Di mana tempat favorit bagi para programmer untuk berkumpul, berdiskusi, dan mencari solusi saat kode mereka error fatal?", options: ["Instagram", "Stack Overflow", "TikTok", "Pasar Malam"], answer: 1 },
    { question: "Kapan waktu di mana otak seorang programmer bekerja dengan kecepatan penuh dan tingkat fokus mencapai 200%?", options: ["Jam 8 Pagi", "Saat kuliah berlangsung", "Tengah malam menuju subuh", "Sesaat sebelum liburan"], answer: 2 },
    { question: "Apa kepanjangan internal yang sebenarnya dari CSS menurut keluhan para frontend developer?", options: ["Cascading Style Sheets", "Cascading Stress Systems", "Cari Solusi Sendiri", "Code Sederhana Sekali"], answer: 1 },
    { question: "Apa ketakutan terbesar seorang programmer saat mereka sedang asyik coding berjam-jam di laptop?", options: ["Laptop kemasukan semut", "Mati lampu padahal belum tekan Ctrl + S", "Dipanggil makan oleh ibu", "Diajak main game"], answer: 1 },
    { question: "Mengapa kopi hitam dianggap sebagai minuman wajib dan ramuan sihir bagi para software engineer?", options: ["Biar rasanya pahit seperti hidup", "Mengubah kafein menjadi baris-baris kode program", "Harganya murah", "Disuruh oleh dosen pengampu"], answer: 1 },
    { question: "Apa arti status 'P' yang dikirimkan oleh klien atau dosen di ruang chat menurut sudut pandang anak IT?", options: ["Ping / Tes Koneksi", "Penting", "Pusing", "Panggilan Jiwa"], answer: 0 },
    { question: "Mengapa programmer lebih suka menghitung sesuatu dimulai dari angka 0 daripada angka 1?", options: ["Biar beda dari anak akuntansi", "Karena array dan memori komputer mendefinisikannya begitu", "Iseng saja", "Perintah dari bos"], answer: 1 },
    { question: "Apa istilah yang tepat jika sebuah program web buatanmu berjalan lancar di komputermu sendiri tapi error di komputer dosen?", options: ["Dosennya yang salah", "Webnya pilih kasih", "It's works on my machine!", "Komputer dosen terkena hack"], answer: 2 },
    { question: "Mengapa jendela rumah seorang programmer jarang sekali dibuka lebar-lebar?", options: ["Takut kemalingan", "Karena mereka lebih suka Windows yang digital", "Biar kamarnya dingin", "Malas menyentuhnya"], answer: 1 },
    { question: "Apa musuh bebuyutan dari sebuah semicolon (titik koma `;`) di bahasa pemrograman seperti C++ atau Java?", options: ["Kurung kurawal", "Spasi ganda", "Lupa mengetikkannya di akhir baris", "Tanda tanya"], answer: 2 },
    { question: "Benda mati apa di meja kerja yang sering diajak bicara serius oleh programmer saat mencari bug program?", options: ["Gelas Kopi", "Bebek Karet (Rubber Ducking)", "Keyboard", "Mousepad"], answer: 1 }
];